site_name: Веб-сервис для заселения в общежития
nav:
 - Home: index.md

 - Api:
     - "api/hostels/all[GET]": api/hostels.md
     - "api/hostels/all/<int:pk>/[GET]": api/hostels-id.md
     - "api/payments/all[GET]": api/payment.md
     - "api/payments/all/<int:pk>/[GET]": api/payment-id.md
     - "api/payments/create[POST]": api/payment-create.md
     - "api/payments/update/<int:pk>/[PUT]": api/payment-update.md
     - "api/residents/all[GET]": api/resident.md
     - "api/residents/all/<int:pk>/[GET]": api/resident-id.md
     - "api/residents/create[POST]": api/resident-create.md
     - "api/residents/update/<int:pk>/[PUT]": api/resident-update.md
     - "api/checkin/all[GET]": api/checkin.md
     - "api/checkin/create[POST]": api/checkin-create.md
     - "api/checkin/delete/<int:pk>/[DELETE]": api/checkin-delete.md
     - "api/checkin/update/<int:pk>/[PATCH]": api/checkin-update.md
     - "api/rooms/all[GET]": api/room.md
     - "api/rooms/update/<int:pk>/[PUT]": api/room-update.md
 - Front:
     - "/signin/[POST]": front/authtorization.md
     - "/signup/[POST]": front/registration.md
     - "/profile/[PUT]": front/profile.md
     - "/start/[GET]": front/start.md
     - "/users/[GET]": front/users.md
     - "/hostels/[GET]": front/hostels.md
     - "/rooms/:id[GET]": front/rooms.md
     - "/payments/:id[GET]": front/payment.md
     - "/checkin/:id[GET]": front/checkin.md
     - "/movein/:id[POST]": front/checkin-create.md
     - "/payupdate/:id[PUT]": front/pay-update.md
     - "/paymentscreate/:id[POST]": front/pay-create.md

theme:
 name: materia

