# Generated by Django 4.1.6 on 2023-02-13 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_in_app', '0003_transporttype_transport_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transporttype',
            old_name='high',
            new_name='high_max',
        ),
        migrations.AddField(
            model_name='transporttype',
            name='high_min',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
