# Generated by Django 4.1.6 on 2023-02-13 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_in_app', '0004_rename_high_transporttype_high_max_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transporttype',
            old_name='length',
            new_name='max_length',
        ),
        migrations.RenameField(
            model_name='transporttype',
            old_name='weight',
            new_name='max_weight',
        ),
        migrations.AddField(
            model_name='transporttype',
            name='min_length',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transporttype',
            name='min_weight',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
