# Generated by Django 4.1.6 on 2023-02-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_in_app', '0007_transport_high_transport_length_transport_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
