# Generated by Django 4.1.6 on 2023-02-22 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_in_app', '0014_remove_resident_children_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check_in_out',
            name='resident_id',
        ),
        migrations.RemoveField(
            model_name='check_in_out',
            name='room_id',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='address_id',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='organization_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='check_in_out_id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='hostel_id',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Check_in_out',
        ),
        migrations.DeleteModel(
            name='Hostel',
        ),
        migrations.DeleteModel(
            name='Organizatoin',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
