# Generated by Django 4.1.6 on 2023-02-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_project', '0005_rename_length_transporttype_max_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporttype',
            name='logo',
            field=models.TextField(blank=True),
        ),
    ]
