# Generated by Django 4.1.6 on 2023-02-15 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_project', '0008_order_order_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_end',
            field=models.TimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_start',
            field=models.TimeField(default=datetime.date.today),
        ),
    ]
