# Generated by Django 4.1.6 on 2023-02-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_project', '0013_alter_order_time_end_alter_order_time_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='children',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='educational_institution',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='organization_id',
        ),
        migrations.AddField(
            model_name='resident',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
